name: cd
on:
  # this action will only run on each push to master, if you prefer continuous deployment
  push:
    branches: ["master"]

jobs:
  build-publish-deploy:
    name: Build, Publish
    runs-on: ubuntu-latest
    environment: live
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Build and publish the Docker image to the GCP Artifact Registry
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GCP_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_GH_SA_KEY }}
      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.GCP_ARTIFACT_REPO }}waste-sorter:${{ github.sha }}

      # Setup gcloud CLI
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_GH_SA_KEY }}"

      # wait for the image to be available in the registry
      - name: "sleep"
        run: 'sleep 10'

      # not passing `-allow-unauthenticated` flag here because it is recommended to not let the CD pipeline take the responsibility of setting up authentication
      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "${{ secrets.CLOUDRUN_SERVICE }}"
          image: "${{ secrets.GCP_ARTIFACT_REPO }}waste-sorter:${{ github.sha }}"
          # env_vars: |
          #   SOME_ENV_VAR=true
          flags: "--port=5000"
          region: "${{ secrets.GCP_REGION }}"

      - name: "deploy output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'